name: node-ci-pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: select the enviroment
        required: true
        default: "development"
        type: choice
        options:
          - development
          - production
      port:
        description: select the port
        required: true
        default: "8080"
  

jobs:
  node:
    runs-on: ["Lix-ubuntu"]
  
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 20
        
    - run: npm install

    - name: run application
      run: |
          node server.js ${{github.event.inputs.environment}} &
          echo "Running environment: $APP_ENV"
          
          node server.js &
          SERVER_PID=$!

          echo "Waiting for application..."
          sleep 5

          echo "Testing application..."
          curl --fail http://localhost${{github.event.inputs.port}}

          echo "Testing health endpoint..."
          curl --fail http://localhost${{github.event.inputs.port}}/health

          echo "Stopping server..."
          kill $SERVER_PID
