name: node-ci-pipeline

on:
  push:
    branches: ["main"]

jobs:
  node:
    runs-on: ["Lix-ubuntu"]
  
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: 'npm'
    - run: npm install
    - run: npm run test

    - name: run application
      run:
          node server.js &
          sleep 5
          curl http://localhost:8080
          curl http://localhost:8080/heath 
          pkill -f "node server.js"
